AWSTemplateFormatVersion: '2010-09-09'
Description: 'AllSenses AI Guardian - SMS Lambda with Function URL (Production)'

Resources:
  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SNSPublishPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: '*'

  # Lambda Function
  SMSLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: allsenses-sms-production
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Placeholder - will be updated with actual code'
              }
      Environment:
        Variables:
          ENVIRONMENT: production
          LOG_LEVEL: INFO

  # Lambda Function URL
  SMSLambdaFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt SMSLambdaFunction.Arn
      AuthType: NONE  # Public access (protected by CORS)
      Cors:
        AllowOrigins:
          - '*'
        AllowMethods:
          - POST
        AllowHeaders:
          - Content-Type
        MaxAge: 300

  # Permission for Function URL to invoke Lambda
  SMSLambdaFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SMSLambdaFunction
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

Outputs:
  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref SMSLambdaFunction
    Export:
      Name: !Sub '${AWS::StackName}-FunctionName'

  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt SMSLambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'

  FunctionUrl:
    Description: Lambda Function URL (use this in frontend)
    Value: !GetAtt SMSLambdaFunctionUrl.FunctionUrl
    Export:
      Name: !Sub '${AWS::StackName}-FunctionUrl'

  ExecutionRoleArn:
    Description: Lambda Execution Role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ExecutionRoleArn'
